#pragma once
#define G4VOX_VERSION_MAJOR @G4Vox_VERSION_MAJOR@
#define G4VOX_VERSION_MINOR @G4Vox_VERSION_MINOR@
#define G4VOX_VERSION_PATCH @G4Vox_VERSION_PATCH@
#define G4VOX_VERSION "@G4Vox_VERSION@"
